### ISSUE TITLE
Is it possible to use react-router-dom hooks inside breadcrumb component ?

### ISSUE THREAD

**Issue by Its-Alex** [icd2k3/use-react-router-breadcrumbs#11]
Hi,

I would like to know if this is possible to use `react-router-dom hooks` inside a breadcrumb component, for example:

```javascript
import useBreadcrumbs from 'use-react-router-breadcrumbs';
import { useParams } from 'react-router-dom';

const userNamesById = { '1': 'John' }

const DynamicUserBreadcrumb = () => {
  const { userId } = useParams();
  return (
    <span>{userNamesById[userId]}</span>
  );
};

// define custom breadcrumbs for certain routes.
// breadcumbs can be components or strings.
const routes = [
  { path: '/users/:userId', breadcrumb: DynamicUserBreadcrumb },
  { path: '/example', breadcrumb: 'Custom Example' },
];

// map & render your breadcrumb components however you want.
const Breadcrumbs = () => {
  const breadcrumbs = useBreadcrumbs(routes);

  return (
    <>
      {breadcrumbs.map(({
        match,
        breadcrumb
      }) => (
        <span key={match.url}>
          <NavLink to={match.url}>{breadcrumb}</NavLink>
        </span>
      ))}
    </>
  );
};
```

When I try this code above I receive nothing from `useParams` is it normal? Is there a way to make it works?

**Comment by icd2k3** [comment]
Hi @Its-Alex - there is currently no good way to support this because `useParams` has to be a component nested within the corresponding `<Route />` component ([see this example](https://reacttraining.com/react-router/web/api/Hooks/useparams)).

Each dynamic breadcrumb will have a `match.params` object which will have the data you're looking for, though!

**Comment by Its-Alex** [comment]
@icd2k3 Okay, thanks for the answer
